-- MySQL Script generated by MySQL Workbench
-- 06/13/20 20:31:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `Idclients` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Andreca` VARCHAR(45) NULL,
  `Telefon` DECIMAL NULL,
  `Email` VARCHAR(45) NULL,
  `Datareg` DECIMAL NULL,
  `Recomanat` VARCHAR(45) NULL,
  PRIMARY KEY (`Idclients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ulleres` (
  `Id_ulleres` INT NOT NULL,
  `Color m` VARCHAR(45) NULL,
  `Montatura` VARCHAR(45) NULL,
  `Graduacio` DECIMAL NULL,
  `Color v` VARCHAR(45) NULL,
  `Preu` DECIMAL NULL,
  `Client_idclients` INT NULL,
  `clients_Idclients` INT NOT NULL,
  PRIMARY KEY (`Id_ulleres`),
  INDEX `fk_ulleres_clients1_idx` (`clients_Idclients` ASC),
  CONSTRAINT `fk_ulleres_clients1`
    FOREIGN KEY (`clients_Idclients`)
    REFERENCES `mydb`.`clients` (`Idclients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveidor` (
  `Idproveidor` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Adreca` VARCHAR(45) NULL,
  `Fax` VARCHAR(45) NULL,
  `Nif` VARCHAR(45) NULL,
  `Marca_idmarca` INT NOT NULL,
  `Ulleres_idmarca` INT NOT NULL,
  `ulleres_Id_ulleres` INT NOT NULL,
  PRIMARY KEY (`Idproveidor`),
  INDEX `fk_proveidor_ulleres_idx` (`ulleres_Id_ulleres` ASC),
  CONSTRAINT `fk_proveidor_ulleres`
    FOREIGN KEY (`ulleres_Id_ulleres`)
    REFERENCES `mydb`.`ulleres` (`Id_ulleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `Idmarca` INT NOT NULL,
  `Graduacio` VARCHAR(45) NULL,
  `Color m` VARCHAR(45) NULL,
  `Color v` VARCHAR(45) NULL,
  `Montatura` VARCHAR(45) NULL,
  `Preu` DECIMAL NULL,
  `proveidor_Idproveidor` INT NOT NULL,
  PRIMARY KEY (`Idmarca`),
  INDEX `fk_marca_proveidor1_idx` (`proveidor_Idproveidor` ASC),
  CONSTRAINT `fk_marca_proveidor1`
    FOREIGN KEY (`proveidor_Idproveidor`)
    REFERENCES `mydb`.`proveidor` (`Idproveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleat` (
  `idempleat` INT NOT NULL,
  `Idventa` INT NOT NULL,
  `clients_Idclients` INT NOT NULL,
  PRIMARY KEY (`idempleat`, `Idventa`),
  INDEX `fk_empleat_clients1_idx` (`clients_Idclients` ASC),
  CONSTRAINT `fk_empleat_clients1`
    FOREIGN KEY (`clients_Idclients`)
    REFERENCES `mydb`.`clients` (`Idclients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
